services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      USERNAME: "cyber"         # optional login user
      PASSWORD: "cyber@123"     # optional login password
      RAM_SIZE: "6G"
      CPU_CORES: "4"
      DISK_SIZE: "100G"          # main C: drive
      DISK2_SIZE: "100G"        # second D: drive
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - ./windows:/storage      # persistent storage for VM
      - ./data:/data            # extra host folder mounted as shared drive
    restart: always
    stop_grace_period: 2m
